version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: "4c490893-1088-44e7-acb5-8fa9b3531cd5"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
