version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 09754702-c3c1-4470-aa75-2f34fa8de554
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
