version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 4518e3d2-af55-4edc-9ea6-46f6db4692de
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
